[project]
name = "nabchan-mcp-server"
version = "0.1.0"
description = "Nablarchの解説書をもとにしてNablarchの情報を返すMCPサーバーです"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiofiles>=24.1.0",
    "beautifulsoup4>=4.13.3",
    "html2text>=2024.2.26",
    "janome>=0.5.0",
    "langchain-openai>=0.3.12",
    "mcp[cli]>=1.6.0",
    "pydantic>=2.11.2",
    "python-dotenv>=1.1.0",
    "tiktoken>=0.9.0",
    "tqdm>=4.67.1",
    "whoosh-reloaded>=2.7.5",
]

[dependency-groups]
dev = [
    "taskipy>=1.14.1",
]

[tool.taskipy.tasks]
fix = "uvx ruff format && uvx ruff check --fix"