name: Deploy container image to container registry

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

permissions:
  packages: write

jobs:
  lint:
    name: static analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          submodules: false
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: setup uv and venv
        run: |
          pip install uv
          uv sync
      - name: lint
        run: |
          uvx ruff format --check
          uvx ruff check

  deploy:
    name: Build container image
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
      - uses: actions/checkout@v4
        with: 
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: setup uv and venv
        run: |
          pip install uv
          uv sync
      - name: build index
        run: |
          uv run -m tools.build_index
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - name: docker build and push
        env:
          CONTAINER_IMAGE: ghcr.io/backpaper0/nabchan-mcp-server
        run: |
          docker --version
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u backpaper0 --password-stdin
          docker build --pull -t $CONTAINER_IMAGE:latest .
          docker push $CONTAINER_IMAGE:latest
          docker tag $CONTAINER_IMAGE:latest $CONTAINER_IMAGE:${{ github.ref_name }}
          docker push $CONTAINER_IMAGE:${{ github.ref_name }}
